image: node:18-alpine

# Variables globales
variables:
  FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
  FIREBASE_TOKEN: $FIREBASE_TOKEN
  NODE_ENV: production

# Cache pour optimiser les builds
cache:
  paths:
    - back/functions/node_modules/
    - .npm/

# Définition des stages
stages:
  - install
  - lint
  - test
  - security
  - build
  - deploy-staging
  - deploy-production

# Installation des dépendances
install_dependencies:
  stage: install
  before_script:
    - cd back/functions
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "Dependencies installed successfully"
  artifacts:
    paths:
      - back/functions/node_modules/
    expire_in: 1 hour

# Linting du code
lint_code:
  stage: lint
  dependencies:
    - install_dependencies
  before_script:
    - cd back/functions
  script:
    - npm run lint
  allow_failure: false

# Tests unitaires
test_unit:
  stage: test
  dependencies:
    - install_dependencies
  before_script:
    - cd back/functions
  script:
    - npm test -- --coverage --watchAll=false
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: back/functions/coverage/cobertura-coverage.xml
    paths:
      - back/functions/coverage/
    expire_in: 1 week
  only:
    - test
    - main
    - merge_requests

# Audit de sécurité
security_audit:
  stage: security
  dependencies:
    - install_dependencies
  before_script:
    - cd back/functions
  script:
    - npm audit --audit-level high
    - npm audit fix --dry-run
  allow_failure: true
  only:
    - test
    - main
    - merge_requests

# Build des functions
build_functions:
  stage: build
  dependencies:
    - install_dependencies
  before_script:
    - cd back/functions
    - npm install -g firebase-tools
  script:
    - npm run build
    - echo "Firebase functions built successfully"
  artifacts:
    paths:
      - back/functions/lib/
    expire_in: 1 hour
  only:
    - test
    - main

# Déploiement en staging (branche test)
deploy_staging:
  stage: deploy-staging
  dependencies:
    - build_functions
  before_script:
    - cd back
    - npm install -g firebase-tools
    - firebase use $FIREBASE_PROJECT_STAGING_ID --token $FIREBASE_TOKEN
  script:
    - firebase deploy --only functions --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_STAGING_ID
    - echo "Deployed to staging environment"
  environment:
    name: staging
    url: https://$FIREBASE_PROJECT_STAGING_ID.web.app
  only:
    - test
  when: manual

# Déploiement en production (branche main)
deploy_production:
  stage: deploy-production
  dependencies:
    - build_functions
  before_script:
    - cd back
    - npm install -g firebase-tools
    - firebase use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  script:
    - firebase deploy --only functions --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
    - echo "Deployed to production environment"
  environment:
    name: production
    url: https://$FIREBASE_PROJECT_ID.web.app
  only:
    - main
  when: manual
  allow_failure: false

# Job de rollback en cas de problème
rollback_production:
  stage: deploy-production
  before_script:
    - cd back
    - npm install -g firebase-tools
    - firebase use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  script:
    - firebase functions:config:clone --from $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
    - echo "Rollback completed"
  environment:
    name: production
  only:
    - main
  when: manual
  allow_failure: false

# Job de nettoyage des anciens déploiements
cleanup_old_versions:
  stage: deploy-production
  before_script:
    - cd back
    - npm install -g firebase-tools
  script:
    - firebase functions:list --token $FIREBASE_TOKEN
    - echo "Cleanup completed"
  only:
    - main
  when: manual
  allow_failure: true