image: node:18-alpine

variables:
  FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
  FIREBASE_PROJECT_STAGING_ID: $FIREBASE_PROJECT_STAGING_ID
  FIREBASE_TOKEN: $FIREBASE_TOKEN
  NODE_ENV: production
  HUSKY: 0 # IMPORTANT: désactive Husky dans le CI

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - back/node_modules/
    - front/node_modules/
    - .npm/

stages:
  - install
  - lint
  - test
  - build
  - deploy-staging
  - deploy-production

before_script:
  - npm install -g firebase-tools --no-fund --no-audit

# --- Install Backend ---
install_backend_dependencies:
  stage: install
  script:
    - cd back
    - npm ci --prefer-offline --silent
    - echo "Backend dependencies installed"
  artifacts:
    paths:
      - back/node_modules/
    expire_in: 1h

# --- Install Frontend ---
install_frontend_dependencies:
  stage: install
  script:
    - cd front
    - npm ci --prefer-offline --silent
    - echo "Frontend dependencies installed"
  artifacts:
    paths:
      - front/node_modules/
    expire_in: 1h

# --- Lint Backend ---
lint_backend:
  stage: lint
  dependencies:
    - install_backend_dependencies
  script:
    - cd back/functions
    - npx eslint -c .eslintrc.json . --max-warnings=0
  allow_failure: false

# --- Lint Frontend ---
lint_frontend:
  stage: lint
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npx eslint -c eslint.config.cjs . --ext .js,.jsx,.ts,.tsx --max-warnings=0
  allow_failure: false

# --- Test Backend ---
test_backend:
  stage: test
  dependencies:
    - install_backend_dependencies
  script:
    - cd back
    - npm test
  allow_failure: false

# --- Test Frontend ---
test_frontend:
  stage: test
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npx vitest run
  allow_failure: false

# --- Build Backend ---
build_backend:
  stage: build
  dependencies:
    - install_backend_dependencies
  script:
    - cd back
    - npm run lint
    - echo "Backend linted"
  artifacts:
    paths:
      - back/dist/
    expire_in: 2h
  only:
    - main

# --- Build Frontend ---
build_frontend:
  stage: build
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npm run build
    - echo "Frontend built"
  artifacts:
    paths:
      - front/dist/
    expire_in: 2h
  only:
    - main

# --- Deploy Staging ---
deploy_staging:
  stage: deploy-staging
  dependencies:
    - build_backend
    - build_frontend
  script:
    - firebase use $FIREBASE_PROJECT_STAGING_ID --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_STAGING_ID
  environment:
    name: staging
    url: https://$FIREBASE_PROJECT_STAGING_ID.web.app
  only:
    - test
  when: manual

# --- Deploy Production ---
deploy_production:
  stage: deploy-production
  dependencies:
    - build_backend
    - build_frontend
  script:
    - firebase use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
  environment:
    name: production
    url: https://$FIREBASE_PROJECT_ID.web.app
  only:
    - main
  when: manual
