image: node:18-alpine

variables:
  FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
  FIREBASE_PROJECT_STAGING_ID: $FIREBASE_PROJECT_STAGING_ID
  FIREBASE_TOKEN: $FIREBASE_TOKEN
  NODE_ENV: production

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - back/functions/node_modules/
    - front/node_modules/
    - .npm/

stages:
  - install
  - lint
  - test
  - security
  - build
  - deploy-staging
  - deploy-production

# global prereq (firebase cli)
before_script:
  - npm install -g firebase-tools --no-audit --no-fund

# -------------------------
# Install dependencies
# -------------------------
install_backend_dependencies:
  stage: install
  script:
    - cd back/functions
    - npm ci --silent --prefer-offline
    - echo "Backend (functions) deps installed"
  artifacts:
    paths:
      - back/functions/node_modules/
    expire_in: 1h

install_frontend_dependencies:
  stage: install
  script:
    - cd front
    - npm ci --silent --prefer-offline
    - echo "Frontend deps installed"
  artifacts:
    paths:
      - front/node_modules/
    expire_in: 1h

# -------------------------
# Lint
# -------------------------
lint_backend:
  stage: lint
  dependencies:
    - install_backend_dependencies
  script:
    - cd back/functions
    # use the local ESLint installed by npm ci (works if eslint is in devDependencies)
    - npx eslint . --max-warnings=0
  allow_failure: false

lint_frontend:
  stage: lint
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npx eslint . --max-warnings=0
  allow_failure: false

# -------------------------
# Tests
# -------------------------
test_backend:
  stage: test
  dependencies:
    - install_backend_dependencies
  script:
    - cd back/functions
    - npm test -- --coverage --watchAll=false || true
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: back/functions/coverage/cobertura-coverage.xml
    paths:
      - back/functions/coverage/
    expire_in: 1w
  only:
    - main
    - test
    - merge_requests

test_frontend:
  stage: test
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npm run test -- --coverage --watchAll=false || true
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: front/coverage/cobertura-coverage.xml
    paths:
      - front/coverage/
    expire_in: 1w
  only:
    - main
    - test
    - merge_requests

# -------------------------
# Security audits (non-blocking)
# -------------------------
security_audit_backend:
  stage: security
  dependencies:
    - install_backend_dependencies
  script:
    - cd back/functions
    - npm audit --audit-level high || true
    - npm audit fix --dry-run || true
  allow_failure: true
  only:
    - main
    - test
    - merge_requests

security_audit_frontend:
  stage: security
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npm audit --audit-level high || true
    - npm audit fix --dry-run || true
  allow_failure: true
  only:
    - main
    - test
    - merge_requests

# -------------------------
# Build
# -------------------------
build_backend:
  stage: build
  dependencies:
    - install_backend_dependencies
  script:
    - cd back/functions
    - npm run build || echo "No build script for backend/functions"
    - echo "Backend build step finished"
  artifacts:
    paths:
      - back/functions/lib/
    expire_in: 2h
  only:
    - main
    - test

build_frontend:
  stage: build
  dependencies:
    - install_frontend_dependencies
  script:
    - cd front
    - npm run build
    - echo "Frontend built"
  artifacts:
    paths:
      - front/dist/
    expire_in: 2h
  only:
    - main
    - test

# -------------------------
# Deploys (manual)
# -------------------------
deploy_staging:
  stage: deploy-staging
  dependencies:
    - build_backend
    - build_frontend
  script:
    - firebase deploy --project $FIREBASE_PROJECT_STAGING_ID --token $FIREBASE_TOKEN
  environment:
    name: staging
    url: https://$FIREBASE_PROJECT_STAGING_ID.web.app
  only:
    - test
  when: manual

deploy_production:
  stage: deploy-production
  dependencies:
    - build_backend
    - build_frontend
  script:
    - firebase deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  environment:
    name: production
    url: https://$FIREBASE_PROJECT_ID.web.app
  only:
    - main
  when: manual

deploy_functions_only:
  stage: deploy-production
  dependencies:
    - build_backend
  script:
    - firebase deploy --only functions --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  environment:
    name: production
  only:
    - main
  when: manual

deploy_hosting_only:
  stage: deploy-production
  dependencies:
    - build_frontend
  script:
    - firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  environment:
    name: production
  only:
    - main
  when: manual
